# Generated by Django 3.1.3 on 2020-11-19 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201119_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='noote',
            new_name='note',
        ),
    ]
